server:
  port: 9996
spring:
  application:
    name: eruka

# 通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
#  eureka.client.fetchRegistry：false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  